version: '3'
services:
  mysql:
    image: mysql:8 #utilizing mysql image
    container_name: instant-messaging-system-mysql #the name to start a mysql image instance
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #password of root user
    ports:
      - "3307:3306" #port of mysql
    volumes:
      - ./.mysql-data:/var/lib/mysql
#      - ./mysql-init:/docker-entrypoint-initdb.d #run script
    restart: always #automatically restart if container stop or fails
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:6.2.6
    container_name: instant-messaging-system-redis
    ports:
      - "6379:6379"
    volumes:
      - ./.redis-data:/data
  rabbitmq:
    image: rabbitmq:3.12.6-management
    container_name: instant-messaging-system-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" #rabbit mq dashboard port
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq #persistency
  minio:
    image: "quay.io/minio/minio:RELEASE.2022-08-02T23-59-16Z"
    container_name: minio
    ports:
      - "9000:9000" # api port
      - "9001:9001" # console port
    environment:
      MINIO_ROOT_USER: admin # console dashboard username
      MINIO_ROOT_PASSWORD: 12345678 # console dashboard username'spassword
      MINIO_COMPRESS: "off" # turn on/off compress
      MINIO_COMPRESS_EXTENSIONS: ""
      MINIO_COMPRESS_MIME_TYPES: ""
    volumes:
      - ./minio/data:/data/ # mapping the container's data directory to the current data directory
      - ./minio/config:/root/.minio/ # mapping configuration file
    command: server --address ':9000' --console-address ':9001' /data
    privileged: true

