spring:
  profiles:
    active: test #test envrionment
  application:
    name: instant-messaging-system
  datasource:
    url: jdbc:mysql://${imsystem.mysql.ip}:${imsystem.mysql.port}/${imsystem.mysql.db}?useUnicode=true&characterEncoding=UTF-8
    username: ${imsystem.mysql.username}
    password: ${imsystem.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
     matching-strategy: ANT_PATH_MATCHER
  redis:
    host: ${imsystem.redis.host} #redis service address
    port: ${imsystem.redis.port} #redis port
    database: 0
    timeout: 1800000
    password: ${imsystem.redis.password}
    lettuce:
      pool:
        max-wait: -1
        max-idle: 5
        min-idle: 0
        max-active: 20
  jackson:
    serialization:
      write-dates-as-timestamps: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
wx:
  mp:
    callback: ${imsystem.wx.callback}
    configs:
      - appId: ${imsystem.wx.appId}
        secret: ${imsystem.wx.secret}
        token: ${imsystem.wx.token}
        aesKey: ${imsystem.wx.aesKey}
jwt:
  secret: ${imsystem.jwt.token}
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true